name: Linting

on:
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]

jobs:
  format:
    name: Linting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "pip"

    - name: Install PDM
      run: |
        python -m pip install --upgrade pip
        pip install pdm

    - name: Install Dependencies
      run: pdm install -G linting

    - name: Black
      run: pdm run black --check ./src

    - name: Ruff
      run: pdm run ruff check ./src

    - name: ISort
      run: pdm run isort --check ./src

    - name: MyPy
      run: pdm run mypy ./src

    - name: Cache PDM
      uses: actions/cache@v4
      with:
        path: ./__pypackages__
        key: ${{ runner.os }}-pdm-${{ hashFiles('**/pdm.lock') }}
        restore-keys: |
          ${{ runner.os }}-pdm-
